# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- users/svelderrain/deployment-experiment

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Execute Batch File1'
  inputs:
    targetType: 'inline'
    script: |
      # Define the path to the batch file
      $batchFilePath = "$(Build.SourcesDirectory)\Tooling\deployment\buildniiconeditor64LVAddonVIPackage.bat"
      
      # Ensure the file exists
      if (Test-Path $batchFilePath) {
          # Execute the batch file
          & $batchFilePath
      } else {
          Write-Error "Batch file not found at $batchFilePath"
      }
- task: PowerShell@2
  displayName: 'Execute Batch File2'
  inputs:
    targetType: 'inline'
    script: |
      # Define the path to the batch file
      $batchFilePath = "$(Build.SourcesDirectory)\Tooling\deployment\test.bat"
      
      # Ensure the file exists
      if (Test-Path $batchFilePath) {
          # Execute the batch file
          & $batchFilePath
      } else {
          Write-Error "Batch file not found at $batchFilePath"
      }
# Batch script
  # Run a Windows command or batch script and optionally allow it to change the environment
- task: BatchScript@1
  displayName: 'Execute Batch File3'
    inputs:
      filename: "$(Build.SourcesDirectory)\Tooling\deployment\buildniiconeditor64LVAddonVIPackage.bat"
      arguments: # Optional
      modifyEnvironment: False # Optional
      workingFolder: $(Build.ArtifactStagingDirectory) # Optional
      failOnStandardError: false # Optional