# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

pool:
  vmImage: windows-latest

stages:
- stage: Build_batch_file
  jobs:
  - job: Build_the_damn_thing
    steps: 
    - script: call C:\labview-icon-editor\Tooling\deployment\buildniiconeditor64LVAddonVIPackage.bat
    
