# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: Build batch file
  jobs:
  - job: Build the damn thing
 script: call C:\labview-icon-editor\Tooling\deployment\build niiconeditor64 LVAddon - NIPackage.bat

