# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

name: $(Build.BuildID)

pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'

stages:
- stage: Build_LVAddon_x86
  jobs:
  - template: pipeline\templates\Build_Icon_Editor_Packages.yml
    parameters:
     LVVersion: '2021'
     SupportedBitness: '32'
     ApiVersion: 'v1'
     MinimumSupportedLVVersion: '23.0'
     AddonName: 'niiconeditor32'
     RelativePath: $(Build.Repository.LocalPath)
     BuildSpec: 'Editor Packed Library'
     NIPB_Path: '$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\IconEditorDeployment_x%SupportedBitness%.pbs"'
     Project: '$(Build.Repository.LocalPath)\lv_icon_editor.lvproj'
     PackedProjectLibraryVersion: '1.2.3.1'
     poolName: 'Default'
     projectDemands: 'iconeditor -equals true'