# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

name: $(Build.BuildID)
pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  LabVIEW_Version: 2021
  Architecture: 64
  LabVIEW_Port: 3370
  LabVIEW_Folder: C:\Program Files\National Instruments\LabVIEW
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'

stages:
- stage: Build_LVAddon
  jobs:
  - job: Build_PPL
    steps:
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\ModifyProjectDeployLVAddons.vi" -- [$(Build.Repository.LocalPath)\lv_icon_editor.lvproj", "Editor Packed Library"]

      displayName: 'Modify project to deploy to LVAddons'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: call g-cli --lv-ver 2021 --arch ${{variables.Architecture}} QuitLabVIEW -- -v

      displayName: 'Quit LabVIEW'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch ${{variables.Architecture}} lvbuildspec -- -v 1.1.1.1 -p "$(Build.Repository.LocalPath)\lv_icon_editor.lvproj" -b "Editor Packed Library"

      displayName: 'Build the PPL'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\CreateLVAddonJSONfile.vi"

      displayName: 'Create JSON file on LVAddon'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\DestroyLVINILocalHostKey.vi"

      displayName: 'Remove localhost flag from LabVIEW INI'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script:  g-cli --lv-ver 2021 --arch ${{variables.Architecture}} QuitLabVIEW -- -v

      displayName: 'Quit LabVIEW'
      continueOnError: true
