# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

name: $(Build.BuildID)
pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'

stages:
- stage: Build_LVAddon_x86
  jobs:
  - job: Build_PPL
    steps:
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 32 -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\CreateLVINILocalHostKey.vi" -- "$(Build.Repository.LocalPath)"

      displayName: 'Create localhost flag from LabVIEW INI'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 32 -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\ModifyProjectDeployLVAddons.vi" -- "$(Build.Repository.LocalPath)\lv_icon_editor.lvproj" "Editor Packed Library"

      displayName: 'Modify project to deploy to LVAddons'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: call g-cli --lv-ver 2021 --arch 32 QuitLabVIEW -- -v

      displayName: 'Quit LabVIEW'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 32 lvbuildspec -- -v 1.1.1.1 -p "$(Build.Repository.LocalPath)\lv_icon_editor.lvproj" -b "Editor Packed Library"

      displayName: 'Build the PPL'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 32 -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\CreateLVAddonJSONfile.vi"

      displayName: 'Create JSON file on LVAddon'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 32 -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\DestroyLVINILocalHostKey.vi"

      displayName: 'Remove localhost flag from LabVIEW INI'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: call g-cli --lv-ver 2021 --arch 32 -v vipb -- -av -b "$(Build.Repository.LocalPath)\Tooling\deployment\VIPackage\NI Icon editorx86.vipb"
        
      displayName: 'Build VI Package'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 32 -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\DestroyLVINILocalHostKey.vi"

      displayName: 'Remove localhost flag from LabVIEW INI'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script:  g-cli --lv-ver 2021 --arch 32 QuitLabVIEW -- -v

      displayName: 'Quit LabVIEW'
      continueOnError: true
- stage: Build_LVAddon_x64
  jobs:
  - job: Build_PPL
    steps:
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 64 -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\CreateLVINILocalHostKey.vi" -- "$(Build.Repository.LocalPath)"

      displayName: 'Create localhost flag from LabVIEW INI'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 64 -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\ModifyProjectDeployLVAddons.vi" -- "$(Build.Repository.LocalPath)\lv_icon_editor.lvproj" "Editor Packed Library"

      displayName: 'Modify project to deploy to LVAddons'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: call g-cli --lv-ver 2021 --arch 64 QuitLabVIEW -- -v

      displayName: 'Quit LabVIEW'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 64 lvbuildspec -- -v 1.1.1.1 -p "$(Build.Repository.LocalPath)\lv_icon_editor.lvproj" -b "Editor Packed Library"

      displayName: 'Build the PPL'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 64 -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\CreateLVAddonJSONfile.vi"

      displayName: 'Create JSON file on LVAddon'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: call g-cli --lv-ver 2021 --arch 64 -v vipb -- -av -b "$(Build.Repository.LocalPath)\Tooling\deployment\VIPackage\NI Icon editorx64.vipb"
        
      displayName: 'Build VI Package'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch 64 -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\DestroyLVINILocalHostKey.vi"

      displayName: 'Remove localhost flag from LabVIEW INI'
      continueOnError: true
    - task: CmdLine@2
      inputs:
        script:  g-cli --lv-ver 2021 --arch 64 QuitLabVIEW -- -v

      displayName: 'Quit LabVIEW'
      continueOnError: true
