# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

pool:
  vmImage: windows-latest
System.DefaultWorkingDirectory: C:\labview-icon-editor\Tooling\deployment
steps:
- script: call buildniiconeditor64LVAddonVIPackage.bat
  workingDirectory: $(System.DefaultWorkingDirectory)
