# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

pool:
  vmImage: windows-latest

steps:
# Command Line v2
# Run a command line script using Bash on Linux and macOS and cmd.exe on Windows.
- task: CmdLine@2
  inputs:
    script: Tooling\deployment\buildniiconeditor64LVAddonVIPackage.bat
  # Advanced
    #workingDirectory: C:\labview-icon-editor\Tooling\deployment 
    #failOnStderr: false # boolean. Fail on Standard Error. Default: false.