# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

pool:
  vmImage: windows-latest
  
jobs:

- job: Build_Packed_Project_Library
  displayName: I Like Turtles
  steps: 
  - script: LabVIEWCLI -OperationName RunVI -VIPath "C:\labview-icon-editor\deployment\NIPackage\CreateLVINILocalHostKey.vi" -LabVIEWPath C:\Program Files\National Instruments\LabVIEW 2021\LabVIEW.exe -PortNumber 3370 -LogFilePath "C:\Users\Public\CLIlog1.txt" -Verbosity Diagnostic -LogToConsole TRUE