# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

pool:
  vmImage: windows-latest

steps:
- script: buildniiconeditor64LVAddonVIPackage.bat
  workingDirectory: C:\labview-icon-editor\Tooling\deployment
  displayName: Build 64 bit LabVIEW
  failOnStderr: true