# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- users/svelderrain/deployment-experiment

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Execute Batch File'
  inputs:
    targetType: 'inline'
    script: |
      # Define the path to the batch file
      $batchFilePath = "C:\labview-icon-editor\Tooling\deployment\buildniiconeditor64LVAddonVIPackage.bat"
      
      # Ensure the file exists
      if (Test-Path $batchFilePath) {
          # Execute the batch file
          & $batchFilePath
      } else {
          Write-Error "Batch file not found at $batchFilePath"
      }
- task: PowerShell@2
  displayName: 'Execute Batch File2'
  inputs:
    targetType: 'inline'
    script: |
      # Define the path to the batch file
      $batchFilePath = "$(Build.SourcesDirectory)\Tooling\deployment\test.bat"
      
      # Ensure the file exists
      if (Test-Path $batchFilePath) {
          # Execute the batch file
          & $batchFilePath
      } else {
          Write-Error "Batch file not found at $batchFilePath"
      }