# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

name: $(Build.BuildID)
pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  LabVIEW_Version: 2021
  LabVIEW_Version_B: 2021 --x64 #version with bitness
  LabVIEW_Port: 3370
  LabVIEW_Folder: C:\Program Files\National Instruments\LabVIEW
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'
  Run_Build_Variables: true

stages:
- stage: I_like_turtles
  condition: eq(variables.Run_Build_Variables,true)
  jobs:
  - job: Create_Build_Versions_Artifact
    steps:
    - powershell: |
        $subDirs = $(Get-Childitem "${{ variables.Top_Level_Path }}" -Directory)
        Write-Host "Sub directory paths found: " $subDirs
        $subDirs | ForEach-Object -Process {
          $thisDir = "${{ variables.Top_Level_Path }}\" + $_
          Write-Host "Testing subdirectory: " $thisDir
          echo 'LabVIEWCLI -LabVIEWPath "${{ variables.LabVIEW_Folder }} ${{ variables.LabVIEW_Version }}\LabVIEW.exe" -OperationName RunVI -VIPath "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\Prepare LV to Use Icon Editor Source.vi" -PortNumber ${{ variables.LabVIEW_Port }} $($thisDir) $(Common.TestResultsDirectory)'
          LabVIEWCLI -LabVIEWPath "${{ variables.LabVIEW_Folder }} ${{ variables.LabVIEW_Version }}\LabVIEW.exe" -OperationName RunVI -VIPath "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\Prepare LV to Use Icon Editor Source.vi" -PortNumber ${{ variables.LabVIEW_Port }} $thisDir $(Common.TestResultsDirectory)
        } 
      displayName: 'Unit tests in ${{ variables.Top_Level_Path }}'
      failOnStderr: true
      continueOnError: true
      errorActionPreference: continue
    - task: CmdLine@2
      inputs:
        script: CALL $(Build.Repository.LocalPath)\Tooling\deployment\buildniiconeditor64LVAddonVIPackage.bat

