# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

name: $(Build.BuildID)
pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  LabVIEW_Version: 2021
  Architecture: 64 #bitness
  LabVIEW_Port: 3370
  LabVIEW_Folder: C:\Program Files\National Instruments\LabVIEW
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'

stages:
- stage: Build_LVAddon
  jobs:
  - job: Prepare_LabVIEW_For_Icon_Editor_Source
    steps:
    - powershell: |         
          g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\CreateLVINILocalHostKey.vi"

      displayName: 'Create Localhost.LibraryPaths token on LabVIEW INI ${{ variables.Top_Level_Path }}'
      failOnStderr: true
      continueOnError: true
      errorActionPreference: continue
    - task: CmdLine@2
      inputs:
        script: g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\CreateLVINILocalHostKey.vi"

