# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/svelderrain/deployment-experiment

name: $(Build.BuildID)
pool: 
  name: "Default"
  demands: "iconeditor -equals true"

variables:
  LabVIEW_Version: 2021
  Architecture: 64
  LabVIEW_Port: 3370
  LabVIEW_Folder: C:\Program Files\National Instruments\LabVIEW
  build_id: $(Build.BuildID)
  build_revision: $[counter('buildCounter',1)]
  build_version: '1.0.$(Build.BuildID).$(build_revision)'

stages:
- stage: Build_LVAddon
  jobs:
  - job: Prepare_LabVIEW_For_Icon_Editor_Source
    steps:
    - powershell: |         
          g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\CreateLVINILocalHostKey.vi"

      displayName: 'Create Localhost.LibraryPaths token on LabVIEW INI'
      failOnStderr: true
      continueOnError: true
      errorActionPreference: continue
    - powershell: |         
          g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -v "$(Build.Repository.LocalPath)\Tooling\PrepareIESource.vi"

      displayName: 'Prepare labview to use icon editor to use source code'
      failOnStderr: true
      continueOnError: true
      errorActionPreference: continue
    - powershell: |         
          g-cli --lv-ver 2021 --arch ${{variables.Architecture}} QuitLabVIEW -- -v

      displayName: 'Quit LabVIEW'
      failOnStderr: true
      continueOnError: true
      errorActionPreference: continue
    - powershell: |         
          g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -- -v 1.1.1.1 -p "$(Build.Repository.LocalPath)\lv_icon_editor.lvproj" -b "Editor Packed Library"

      displayName: 'Build the PPL'
      failOnStderr: true
      continueOnError: true
      errorActionPreference: continue
    - powershell: |         
          g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\CreateLVINILocalHostKey.vi"

      displayName: 'Create JSON file on LVAddon'
      failOnStderr: true
      continueOnError: true
      errorActionPreference: continue
    - powershell: |         
          g-cli --lv-ver 2021 --arch ${{variables.Architecture}} -v "$(Build.Repository.LocalPath)\Tooling\deployment\NIPackage\DestroyLVINILocalHostKey.vi"

      displayName: 'Remove localhost flag from LabVIEW INI'
      failOnStderr: true
      continueOnError: true
      errorActionPreference: continue
    - powershell: |         
          g-cli --lv-ver 2021 --arch ${{variables.Architecture}} QuitLabVIEW -- -v

      displayName: 'Quit LabVIEW'
      failOnStderr: true
      continueOnError: true
      errorActionPreference: continue